# Generated by Django 5.1 on 2024-08-30 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.AddField(
            model_name='aluno',
            name='altura',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(null=True),
        ),
    ]
