# Generated by Django 5.1 on 2024-08-30 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0002_remove_aluno_data_nascimento_remove_aluno_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Aluno.aluno')),
            ],
        ),
    ]
