# Generated by Django 5.1 on 2024-08-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0003_interesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interesses',
            old_name='descricao',
            new_name='interesses',
        ),
    ]
