# Generated by Django 5.1 on 2024-08-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aluno', '0006_amigos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=100)),
                ('historia', models.TextField()),
            ],
        ),
    ]
